version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/apis"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/cloudwego/hertz"
      - dependency-name: "go.uber.org/zap"