version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/apis"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "hertz"
      - dependency-name: "lodash"
      - dependency-name: "aws-sdk"