version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/apis"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/srvs"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"