name: 'user-web'
port: 8021

user_srv:
  host: '10.20.244.204'
  port: 50051
  name: 'user-srv'

jwt:
  key: 'km!RU#a*43BsTsBVLQPpmuXI&$BJD%Sz'

redis:
  host: '127.0.0.1'
  port: 6379
  expire: 300

consul:
  host: 127.0.0.1
  port: 8500