name: "Labeler"
on:
  issues:
    types: [ opened, edited, reopened ]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label issues and pull requests
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: labeler
        uses: Resnovas/label-mastermind@1.4.0-alpha.5
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
